import { useReducer, useCallback } from "react";
import { v4 as genId } from "uuid"; // Importing the genId function from uuid

// Define types for Toast
export type Toast = {
  id: string;
  message: string;
  type?: "success" | "error" | "info";
  title?: string;
  description?: string;
  action?: React.ReactNode;
};

export type ToasterToast = Omit<Toast, "id">; // Excluding 'id' from 'ToasterToast'

// Action types for reducer
type ToastAction =
  | { type: "ADD_TOAST"; toast: ToasterToast } // Adding a toast without 'id'
  | { type: "REMOVE_TOAST"; id: string }      // Removing a toast by 'id'
  | { type: "UPDATE_TOAST"; id: string; toast: Partial<Toast> }; // Updating a toast by 'id'

// Reducer to manage toast state
const toastReducer = (state: Toast[], action: ToastAction): Toast[] => {
  switch (action.type) {
    case "ADD_TOAST":
      // Generate ID here, before adding toast
      return [...state, { ...action.toast, id: genId() }];
    case "REMOVE_TOAST":
      return state.filter((toast) => toast.id !== action.id);
    case "UPDATE_TOAST":
      return state.map((toast) =>
        toast.id === action.id ? { ...toast, ...action.toast } : toast
      );
    default:
      return state;
  }
};

// Custom hook to manage toasts
export const useToast = () => {
  const [toasts, dispatch] = useReducer(toastReducer, []); // Initial state as empty array

  // Add a new toast (with an ID generated by the reducer)
  const addToast = useCallback((toast: ToasterToast) => {
    dispatch({ type: "ADD_TOAST", toast });
  }, []);

  // Remove an existing toast by its ID
  const removeToast = useCallback((id: string) => {
    dispatch({ type: "REMOVE_TOAST", id });
  }, []);

  // Update an existing toast by its ID
  const updateToast = useCallback((id: string, toast: Partial<Toast>) => {
    dispatch({ type: "UPDATE_TOAST", id, toast });
  }, []);

  return {
    toasts,
    addToast,
    removeToast,
    updateToast,
  };
};
